### ISSUE TITLE
Deprecated version of the loader-utils package

### ISSUE THREAD

**Issue by rodmax** [sapics/html-minifier-loader#8]
Hi guys. First of all thanks for the useful package
When i update my webpack to version 2.2.1 i got deprecation warning:
```
[13:58:24] Starting 'webpack'...
(node:22879) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
    at Object.parseQuery (/home/max/work/kipod-x/station/ui/node_modules/loader-utils/index.js:78:3)
    at Object.module.exports (/home/max/work/kipod-x/station/ui/node_modules/html-minifier-loader/index.js:13:28)
    at LOADER_EXECUTION (/home/max/work/kipod-x/station/ui/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
    at runSyncOrAsync (/home/max/work/kipod-x/station/ui/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
    at iterateNormalLoaders (/home/max/work/kipod-x/station/ui/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
    at Array.<anonymous> (/home/max/work/kipod-x/station/ui/node_modules/loader-runner/lib/LoaderRunner.js:202:4)
    at Storage.finished (/home/max/work/kipod-x/station/ui/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:15)
    at /home/max/work/kipod-x/station/ui/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:69:9
    at /home/max/work/kipod-x/station/ui/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:416:3)

```
As i understand you need update `loader-utils` package and use it new API
Details here https://github.com/webpack/loader-utils/issues/56

**Comment by sapics** [comment]
Thank you for information!
I have fixed this issue and published v1.4.0.
Could you please test this version in your project?

**Comment by rodmax** [comment]
I just updated to v1.4.0. It seems everything works well: no deprecation, application works.
Thanks

**Comment by sapics** [comment]
Thank you for checking the new version!
